### ISSUE TITLE
Intergate avni-canned-report app to the avni-web-app

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-canned-reports#10]

**Comment by garimadosar5** [comment]
**QA Notes -** 
- There is no way to go back to home page or any other page from canned report page.

**Comment by garimadosar5** [comment]
**QA Notes 2-** 
- In news and broadcast page has username and logout button also along with home page button.
![Screen Shot 2021-12-16 at 9.17.49 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/78821d54-c894-4334-9d80-241ec4d9c90a)

![Screen Shot 2021-12-16 at 9.18.15 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/b19367a6-ded7-4984-83e5-3beb9f416ee1)

**Comment by vindeolal** [comment]
- We don't have login ability on the canned report app therefore logout option is not there. we need to include extra packages to support it. we can include it in later releases.
