### ISSUE TITLE
Filters on Activity Dashboard

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-canned-reports#3]
Ability to choose from filters : Date Range, Location, User, Subject types, Program, Encounter type

Date range to give more convenient options like Yesterday, This week, Last week, This month, Last month, This year, Last year.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Align all the text in the filter and dropdown values to left.
- Filter "days up to today" and "days starting today", in this 1 is always there. Cannot remove this.

**Comment by garimadosar5** [comment]
**QA Notes 2 -** 
Point 2 is not done. Cannot remove 1 using the back button.
https://images.zenhubusercontent.com/427554825/d417fcdb-a098-4c2b-b487-66dddda94638/date_filter.mov

**Comment by vindeolal** [comment]
- You need to select it and then change it. Because the default date is set to the current date hence 1 will always appear you can select it from the mouse and change it.
